<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <gazebo>
        <!-- Differential Drive Plugin -->
        <!--official documentation-->
        <!--https://gazebosim.org/api/sim/8/classgz_1_1sim_1_1systems_1_1DiffDrive.html-->
        <!--this Plugin will publish those topics-->
        <!--/model/bot1/odometry    publisher   gz.msgs.Odometry-->
        <!--/model/bot1/tf          publisher   gz.msgs.Pose_V      publish the transform from frame_id to child_frame_id-->
        <!--/model/bot1/cmd_vel     subscriber  gz.msgs.Twist    -->
        <!--/model/bot1/enable      subscriber  gz.msgs.Boolean-->
        <plugin filename="gz-sim-diff-drive-system"
                name="gz::sim::systems::DiffDrive">
            <left_joint>chassis_rear_left_wheel</left_joint>
            <right_joint>chassis_rear_right_wheel</right_joint>
            <wheel_separation>${chassis_width + wheel_thickness}</wheel_separation>  <!-- track width -->
            <wheel_radius>${wheel_radius}</wheel_radius>

            <!-- Control parameters -->
<!--            <odom_publish_frequency>50</odom_publish_frequency>-->
<!--            <max_linear_acceleration>1.0</max_linear_acceleration>-->
<!--            <min_linear_acceleration>-1.0</min_linear_acceleration>-->
<!--            <max_angular_acceleration>2.0</max_angular_acceleration>-->
<!--            <min_angular_acceleration>-2.0</min_angular_acceleration>-->
<!--            <max_linear_velocity>0.5</max_linear_velocity>-->
<!--            <min_linear_velocity>-0.5</min_linear_velocity>-->
<!--            <max_angular_velocity>1.0</max_angular_velocity>-->
<!--            <min_angular_velocity>-1.0</min_angular_velocity>-->

            <!-- Topic configuration -->
<!--            <topic>cmd_vel</topic>-->
<!--            <odom_topic>odom</odom_topic>-->
<!--            @todo tbd if neccessary-->
            <frame_id>odom</frame_id>
            <child_frame_id>base_footprint</child_frame_id>
        </plugin>

        <!-- Joint State Publisher -->
        <!--official documentation-->
        <!--https://gazebosim.org/api/sim/8/classgz_1_1sim_1_1systems_1_1JointStatePublisher.html-->
<!--        <plugin filename="gz-sim-joint-state-publisher-system"-->
<!--                name="gz::sim::systems::JointStatePublisher">-->
<!--&lt;!&ndash;            <joint_name>left_wheel_joint</joint_name>&ndash;&gt;-->
<!--&lt;!&ndash;            <joint_name>right_wheel_joint</joint_name>&ndash;&gt;-->
<!--&lt;!&ndash;            <joint_name>caster_yaw_joint</joint_name>&ndash;&gt;-->
<!--&lt;!&ndash;            <joint_name>caster_wheel_joint</joint_name>&ndash;&gt;-->
<!--        </plugin>-->

        <!-- Pose Publisher (optional, for debugging) -->
<!--        <plugin filename="gz-sim-pose-publisher-system"-->
<!--                name="gz::sim::systems::PosePublisher">-->
<!--            <publish_link_pose>true</publish_link_pose>-->
<!--            <publish_collision_pose>false</publish_collision_pose>-->
<!--            <publish_visual_pose>false</publish_visual_pose>-->
<!--            <publish_nested_model_pose>false</publish_nested_model_pose>-->
<!--            <use_pose_vector_msg>true</use_pose_vector_msg>-->
<!--            <update_frequency>50</update_frequency>-->
<!--        </plugin>-->

    </gazebo>

</robot>