<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="macros_inertial.xacro"/>
    <xacro:include filename="macros_material.xacro"/>

    <xacro:property name="chassis_length" value="0.5"/>
    <xacro:property name="chassis_width" value="0.3"/>
    <xacro:property name="chassis_height" value="0.2"/>

    <xacro:property name="track" value="${chassis_width + wheel_thickness}"/>

    <xacro:property name="wheelbase_length" value="0.3"/>
    <xacro:property name="chassis_mass" value="1.0"/>

    <xacro:property name="wheel_radius" value="0.08"/>
    <xacro:property name="wheel_thickness" value="0.085"/>
    <xacro:property name="wheel_mass" value="0.05"/>

    <xacro:property name="caster_wheel_radius" value="0.04"/>
    <xacro:property name="caster_wheel_mass" value="0.5"/>

    <xacro:property name="lidar_x" value="${wheelbase_length/2 + 0.021 + 0.038/2}"/>
    <xacro:property name="lidar_y" value="${-chassis_width/2 + 0.03 + 0.038/2}"/>
    <xacro:property name="lidar_z" value="${chassis_height+0.02}"/>

    <xacro:property name="gps_x" value="${-wheelbase_length/2 - 0.035}"/>
    <xacro:property name="gps_y" value="${-chassis_width/2 + 0.05}"/>
    <xacro:property name="gps_z" value="${chassis_height+0.10}"/>

    <xacro:property name="imu_x" value="${wheelbase_length/2 -0.115}"/>
    <xacro:property name="imu_y" value="${0.0}"/>
    <xacro:property name="imu_z" value="${chassis_height+0.01}"/>

    <xacro:property name="collision_x" value="${wheelbase_length/2 + 0.16}"/>
    <xacro:property name="collision_y" value="${0}"/>
    <xacro:property name="collision_z" value="${0.07}"/>

    <xacro:property name="camera_width" value="0.1"/>
    <xacro:property name="camera_height" value="0.065"/>
    <xacro:property name="camera_length" value="0.03"/>
    <xacro:property name="camera_mass" value="0.05"/>

    <xacro:property name="camera_x" value="${wheelbase_length/2 + 0.08 + camera_length/2}"/>
    <xacro:property name="camera_y" value="${-chassis_width/2 + 0.16}"/>
    <xacro:property name="camera_z" value="${0.078 + 0.06 + camera_height/2}"/>

    <xacro:property name="lidarAS_width" value="0.076"/>
    <xacro:property name="lidarAS_height" value="0.220"/>
    <xacro:property name="lidarAS_length" value="0.032"/>
    <xacro:property name="lidarAS_mass" value="0.05"/>

    <xacro:property name="lidarAS_x" value="${-wheelbase_length/2 + lidarAS_length/2}"/>
    <xacro:property name="lidarAS_y" value="${chassis_width/2 - 0.04}"/>
    <xacro:property name="lidarAS_z" value="${lidarAS_height/2+chassis_height}"/>
    <!-- MACRO FOR THE WHEELS -->

    <xacro:macro name="wheel" params="prefix reflect_x reflect_y">

        <joint name="base_to_${prefix}_wheel" type="continuous">
            <parent link="chassis"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="${reflect_x * wheelbase_length/2} ${reflect_y * track/2} 0" rpy="0 ${pi/2} ${pi/2}"/>
            <axis xyz="0 1 0"/>
        </joint>

        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 ${pi/2 + reflect_y * pi/2}"/>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 ${pi/2 + reflect_y * pi/2}"/>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>

        <gazebo reference="${prefix}_wheel">
            <material>Gazebo/Blue</material>
        </gazebo>
    </xacro:macro>

    <!-- BASE LINK -->
    <link name="base_footprint"/>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <child link="base_footprint"/>
        <parent link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_link"/>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="chassis">
        <xacro:property name="pose_chassis" value="0 0 ${chassis_height/2}"/>
        <visual>
            <origin xyz="${pose_chassis}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <origin xyz="${pose_chassis}"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${pose_chassis}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Orange</material>
    </gazebo>

    <xacro:wheel prefix="rear_right" reflect_x="-1" reflect_y="1" />
    <xacro:wheel prefix="rear_left" reflect_x="-1" reflect_y="-1" />

    <!-- Yaw link -->
    <link name="caster_yaw_link">
        <inertial>
            <mass value="0.01"/>
            <inertia
                    ixx="1e-5" ixy="0" ixz="0"
                    iyy="1e-5" iyz="0"
                    izz="1e-5"/>
        </inertial>
    </link>

    <!-- Swivel -->

    <!--                xyz="${wheelbase_length/2} 0 ${caster_wheel_radius*2}"-->
    <joint name="caster_yaw_joint" type="continuous">
        <parent link="chassis"/>
        <child  link="caster_yaw_link"/>
        <origin
                xyz="${wheelbase_length/2} 0 0"
                rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>

    <!-- Caster wheel -->
    <link name="caster">
        <xacro:property name="caster_pose" value="0 0 0"/>
        <visual>
            <origin xyz="${caster_pose}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="${caster_pose}" rpy="0 0 0"/>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>

        <xacro:inertial_sphere
                mass="${caster_wheel_mass}"
                radius="${caster_wheel_radius}">
            <origin xyz="${caster_pose}"/>
        </xacro:inertial_sphere>
    </link>

    <!-- Roll -->
    <joint name="caster_wheel_joint" type="continuous">
        <parent link="caster_yaw_link"/>
        <child  link="caster"/>
        <origin xyz="0 0 ${-caster_wheel_radius}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <gazebo reference="caster">
        <mu1>0.6</mu1>
        <mu2>0.6</mu2>
    </gazebo>

</robot>